blueprint:
  name: Hue Wall Module – v20.6
  description: >
    DE: Steuert Hue-Leuchten über ein Wandmodul. Verbesserte v20.6 ohne Cover/Doppelklick.
    EN: Controls Hue lights via wall module. Improved v20.x without cover/double-click.
    Version v20.6 – Bilingual labels, English code comments and debug messages.
  domain: automation
  source_url: https://raw.githubusercontent.com/OlliPolli76/home-assistant-blueprints/main/hue_v20.yaml
  author: OlliPolli76

  input:
    switch_device:
      name: Hue Wall Switch (Z2M) | Hue Wandschalter (Z2M)
      description: >
        EN: Select the Zigbee wall module integrated via MQTT. The MQTT topic is automatically detected from the device.
        
        DE: Wähle das Zigbee-Wandmodul, das über MQTT eingebunden ist. Der MQTT-Topic wird automatisch aus dem Device erkannt.
      selector:
        device:
          integration: mqtt

    z2m_friendly_name:
      name: Zigbee2MQTT Friendly Name (optional)
      description: >
        EN: Only fill in if automatic detection doesn't work. Enter the exact friendly name as configured in Zigbee2MQTT.
        Example: "living_room_switch" for topic "zigbee2mqtt/living_room_switch/action"
        
        DE: Nur ausfüllen, wenn die automatische Erkennung nicht funktioniert. Gib hier den exakten Friendly Name ein, wie er in Zigbee2MQTT konfiguriert ist.
        Beispiel: "wohnzimmer_schalter" für Topic "zigbee2mqtt/wohnzimmer_schalter/action"
      default: ""
      selector:
        text:
          multiline: false

    target_light_left:
      name: Left Light or Group (optional) | Linke Lampe oder Gruppe (optional)
      description: >
        EN: The light or group controlled by the left button. Leave empty if only using right side.
        
        DE: Die Lampe oder Gruppe, die bei linker Betätigung gesteuert wird. Leer lassen wenn nur rechte Seite genutzt wird.
      default: ""
      selector:
        entity:
          domain: light

    reference_light_left:
      name: Reference Light Left (optional) | Referenzlampe links (optional)
      description: >
        EN: Optional: Another light whose brightness is used as reference for the left side.
        
        DE: Optional: Eine andere Lampe, deren Helligkeit als Referenz für die linke Seite dient.
      default: ""
      selector:
        entity:
          domain: light

    dim_dir_left:
      name: Direction Boolean Left (optional) | Richtungs-Boolean links (optional)
      description: >
        EN: Input_boolean to control dimming direction left (up/down). Leave empty if only using right side.
        
        DE: Input_boolean zur Steuerung der Dimmrichtung links (aufwärts/abwärts). Leer lassen wenn nur rechte Seite genutzt wird.
      default: ""
      selector:
        entity:
          domain: input_boolean

    move_speed_left:
      name: Step Size Left | Schrittweite links
      description: >
        EN: How much the brightness changes when holding (left side).
        
        DE: Wie stark sich die Helligkeit bei Halten verändert (linke Seite).
      default: 40
      selector:
        number:
          min: 10
          max: 80
          step: 5

    dim_method_left:
      name: Dimming Method Left | Dimm-Methode links
      description: >
        EN: Method for dimming left – automatic or manually selectable.
        
        DE: Methode zur Dimmung links – automatisch oder manuell wählbar.
      default: auto
      selector:
        select:
          options: [auto, brightness_step, brightness_pct, brightness]

    target_light_right:
      name: Right Light or Group (optional) | Rechte Lampe oder Gruppe (optional)
      description: >
        EN: The light or group controlled by the right button. Leave empty if only using left side.
        
        DE: Die Lampe oder Gruppe, die bei rechter Betätigung gesteuert wird. Leer lassen wenn nur linke Seite genutzt wird.
      default: ""
      selector:
        entity:
          domain: light

    reference_light_right:
      name: Reference Light Right (optional) | Referenzlampe rechts (optional)
      description: >
        EN: Optional: Another light whose brightness is used as reference for the right side.
        
        DE: Optional: Eine andere Lampe, deren Helligkeit als Referenz für die rechte Seite dient.
      default: ""
      selector:
        entity:
          domain: light

    dim_dir_right:
      name: Direction Boolean Right (optional) | Richtungs-Boolean rechts (optional)
      description: >
        EN: Input_boolean to control dimming direction right (up/down). Leave empty if only using left side.
        
        DE: Input_boolean zur Steuerung der Dimmrichtung rechts (aufwärts/abwärts). Leer lassen wenn nur linke Seite genutzt wird.
      default: ""
      selector:
        entity:
          domain: input_boolean

    move_speed_right:
      name: Step Size Right | Schrittweite rechts
      description: >
        EN: How much the brightness changes when holding (right side).
        
        DE: Wie stark sich die Helligkeit bei Halten verändert (rechte Seite).
      default: 40
      selector:
        number:
          min: 10
          max: 80
          step: 5

    dim_method_right:
      name: Dimming Method Right | Dimm-Methode rechts
      description: >
        EN: Method for dimming right – automatic or manually selectable.
        
        DE: Methode zur Dimmung rechts – automatisch oder manuell wählbar.
      default: auto
      selector:
        select:
          options: [auto, brightness_step, brightness_pct, brightness]

    min_brightness:
      name: Minimum Brightness | Mindesthelligkeit
      description: >
        EN: Lower limit for dimming – prevents complete turn-off.
        
        DE: Untergrenze für die Dimmung – verhindert vollständiges Ausschalten.
      default: 5
      selector:
        number:
          min: 1
          max: 50
          step: 1

    log_level:
      name: Log Level | Log-Level
      description: >
        EN: Control the detail level in system log.
        
        DE: Steuerung der Detailtiefe im System-Log.
      default: warning
      selector:
        select:
          options: [aus, debug, info, warning, error]

trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/+/action"

mode: restart
max_exceeded: silent

action:
  # Device filtering: Only process the selected device
  - variables:
      log_level_input: !input log_level
      switch_device_id: !input switch_device
      manual_name: !input z2m_friendly_name
      target_light_left: !input target_light_left
      target_light_right: !input target_light_right
      reference_light_left: !input reference_light_left
      reference_light_right: !input reference_light_right
      dim_dir_left: !input dim_dir_left
      dim_dir_right: !input dim_dir_right
      move_speed_left: !input move_speed_left
      move_speed_right: !input move_speed_right
      dim_method_left: !input dim_method_left
      dim_method_right: !input dim_method_right
      min_brightness: !input min_brightness
      actual_device: "{{ trigger.topic.split('/')[1] }}"
      # Automatic detection: Use device name directly
      auto_device_name: >-
        {{ device_attr(switch_device_id, 'name') | lower | replace(' ', '_') | replace('-', '_') }}
      expected_device: "{{ manual_name if manual_name | length > 0 else auto_device_name }}"
      is_correct_device: "{{ expected_device | lower == actual_device | lower }}"
      log_on: "{{ log_level_input != 'aus' }}"

  # Debug log: Device check
  - choose:
      - conditions: "{{ log_on }}"
        sequence:
          - service: system_log.write
            data:
              message: >
                [Device Check]
                trigger_topic={{ trigger.topic }},
                actual_device={{ actual_device }},
                expected_device={{ expected_device }},
                auto_detected={{ auto_device_name }},
                manual_override={{ manual_name }},
                is_correct={{ is_correct_device }}
              level: "{{ log_level_input }}"

  # Stop if wrong device
  - condition: template
    value_template: "{{ is_correct_device }}"

  # From here on, only actions for the correct device
  - variables:
      trig: "{{ trigger.payload }}"
      is_left: "{{ trig.startswith('left') }}"
      active_light: "{{ target_light_left if is_left else target_light_right }}"
      ref_light: "{{ reference_light_left if is_left else reference_light_right }}"
      use_ref: "{{ ref_light | length > 0 }}"
      active_dir: "{{ dim_dir_left if is_left else dim_dir_right }}"
      speed: "{{ move_speed_left if is_left else move_speed_right }}"
      method: "{{ dim_method_left if is_left else dim_method_right }}"
      max_raw: 254
      current_brightness: >-
        {% set ref = ref_light if use_ref else active_light %}
        {{ state_attr(ref, 'brightness') | int(0) }}
      # Check if sides are configured
      left_side_configured: "{{ target_light_left | length > 0 and dim_dir_left | length > 0 }}"
      right_side_configured: "{{ target_light_right | length > 0 and dim_dir_right | length > 0 }}"

  # Stop if side is not configured
  - choose:
      - conditions: "{{ is_left and not left_side_configured }}"
        sequence:
          - choose:
              - conditions: "{{ log_on }}"
                sequence:
                  - service: system_log.write
                    data:
                      message: "[Ignored] Left side not configured"
                      level: "{{ log_level_input }}"
          - stop: "Left side not configured"
      
      - conditions: "{{ not is_left and not right_side_configured }}"
        sequence:
          - choose:
              - conditions: "{{ log_on }}"
                sequence:
                  - service: system_log.write
                    data:
                      message: "[Ignored] Right side not configured"
                      level: "{{ log_level_input }}"
          - stop: "Right side not configured"

  # Debug log: Trigger
  - choose:
      - conditions: "{{ log_on }}"
        sequence:
          - service: system_log.write
            data:
              message: >
                [Trigger]
                payload={{ trig }},
                is_left={{ is_left }},
                active_light={{ active_light }},
                ref_light={{ ref_light }},
                use_ref={{ use_ref }},
                active_dir={{ active_dir }},
                speed={{ speed }},
                method={{ method }},
                current_brightness={{ current_brightness }}
              level: "{{ log_level_input }}"

  - choose:
      # HOLD Event
      - conditions:
          - condition: template
            value_template: "{{ trig in ['left_hold','right_hold'] }}"
        sequence:
          # Check if at limits and stop if yes
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ current_brightness >= max_raw and is_state(active_dir, 'on') }}"
                sequence:
                  - choose:
                      - conditions: "{{ log_on }}"
                        sequence:
                          - service: system_log.write
                            data:
                              message: "[Min/Max] Maximum reached – Stop dimming"
                              level: "{{ log_level_input }}"
                  - stop: "Maximum reached"

              - conditions:
                  - condition: template
                    value_template: "{{ current_brightness <= min_brightness and is_state(active_dir, 'off') }}"
                sequence:
                  - choose:
                      - conditions: "{{ log_on }}"
                        sequence:
                          - service: system_log.write
                            data:
                              message: "[Min/Max] Minimum reached – Stop dimming"
                              level: "{{ log_level_input }}"
                  - stop: "Minimum reached"

          # Dimming calculation
          - variables:
              going_up: "{{ is_state(active_dir, 'on') }}"
              step: >-
                {% if going_up %}
                  {% set remaining = max_raw - current_brightness %}
                  {{ [speed, [remaining, 0] | max] | min }}
                {% else %}
                  {% set remaining = current_brightness - min_brightness %}
                  {{ -([speed, [remaining, 0] | max] | min) }}
                {% endif %}
              next_bri: "{{ (current_brightness + step) | int }}"
              feats: >-
                {% set ref = ref_light if use_ref else active_light %}
                {{ state_attr(ref, 'supported_features') | int(0) }}
              support_basic: "{{ (feats % 2) > 0 }}"
              support_trans: "{{ ((feats // 64) % 2) > 0 }}"
              dim_key: >-
                {% if method != 'auto' %}
                  {{ method }}
                {% elif support_basic and not support_trans %}
                  brightness
                {% elif support_trans %}
                  brightness_step
                {% else %}
                  brightness_pct
                {% endif %}
              dim_val: >-
                {% if dim_key == 'brightness_pct' %}
                  {{ ((next_bri / max_raw * 100) | round) }}
                {% elif dim_key == 'brightness_step' %}
                  {{ step }}
                {% else %}
                  {{ next_bri }}
                {% endif %}

          # Debug log: Dimming calculation
          - choose:
              - conditions: "{{ log_on }}"
                sequence:
                  - service: system_log.write
                    data:
                      message: >
                        [Dimming Calculation]
                        going_up={{ going_up }},
                        step={{ step }},
                        next_bri={{ next_bri }},
                        dim_key={{ dim_key }},
                        dim_val={{ dim_val }},
                        support_basic={{ support_basic }},
                        support_trans={{ support_trans }},
                        features_raw={{ feats }},
                        lamp={{ active_light }}
                      level: "{{ log_level_input }}"

          # Dim with the detected method
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ dim_key == 'brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ active_light }}"
                    data:
                      transition: 1
                      brightness: "{{ dim_val }}"
              - conditions:
                  - condition: template
                    value_template: "{{ dim_key == 'brightness_pct' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ active_light }}"
                    data:
                      transition: 1
                      brightness_pct: "{{ dim_val }}"
              - conditions:
                  - condition: template
                    value_template: "{{ dim_key == 'brightness_step' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ active_light }}"
                    data:
                      transition: 1
                      brightness_step: "{{ dim_val }}"

      # HOLD_RELEASE Event
      - conditions:
          - condition: template
            value_template: "{{ trig in ['left_hold_release','right_hold_release'] }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ active_light }}"
            data:
              brightness_step: 0
          - service: input_boolean.toggle
            target:
              entity_id: "{{ active_dir }}"
          - choose:
              - conditions: "{{ log_on }}"
                sequence:
                  - service: system_log.write
                    data:
                      message: "[Hold Release] Reset brightness_step + toggle direction"
                      level: "{{ log_level_input }}"

      # PRESS_RELEASE Event
      - conditions:
          - condition: template
            value_template: "{{ trig in ['left_press_release','right_press_release'] }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ active_light }}"
          - choose:
              - conditions: "{{ log_on }}"
                sequence:
                  - service: system_log.write
                    data:
                      message: "[Press Release] Light toggled: {{ active_light }}"
                      level: "{{ log_level_input }}"